### ISSUE TITLE
AttributeError: 'module' object has no attribute 'global_variables_initializer'

### ISSUE THREAD

**Issue by d0znpp** [ikostrikov/TensorFlow-VAE-GAN-DRAW#13]
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    model = VAE(FLAGS.hidden_size, FLAGS.batch_size, FLAGS.learning_rate)
  File "/root/TensorFlow-VAE-GAN-DRAW/vae.py", line 51, in __init__
    self.sess.run(tf.global_variables_initializer())
AttributeError: 'module' object has no attribute 'global_variables_initializer'

**Comment by ikostrikov** [comment]
Update TensorFlow to a more recent version. They introduced this function in 0.12.
