### ISSUE TITLE
deconv vs. conv2d_transpose

### ISSUE THREAD

**Issue by kchen92** [ikostrikov/TensorFlow-VAE-GAN-DRAW#2]
It seems to me that you are using the tensorflow deconv2d which performs a transpose convolution (see conv2d_transpose at https://github.com/tensorflow/tensorflow/blob/4c3b060b9b063a247172c939e0e1314577b581e3/tensorflow/python/ops/nn_ops.py). However, the deconv that we want to perform is an unpooling followed by convolution. Could you clarify whether my understanding is correct? Thanks.

Also relevant: https://github.com/tensorflow/tensorflow/issues/256

**Comment by ikostrikov** [comment]
Yes. That's correct. In some papers it's wrongly called deconvolution so I decided to keep it this way.

For example, they mention it here (Figure 1):
http://arxiv.org/pdf/1511.06434v2.pdf

**Comment by kchen92** [comment]
Ok. I have to do some reading still but I think I get it. Thanks.
