### ISSUE TITLE
ProgressBar issue

### ISSUE THREAD

**Issue by tsitsilin** [ikostrikov/TensorFlow-VAE-GAN-DRAW#8]
I downloaded the package and  upgraded TensorFlow to v0.9. However, the first test run did not work:

```
python main-vae.py -- working_directory /tmp/gan
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "main-vae.py", line 143, in <module>
    pbar = ProgressBar(max_value = FLAGS.updates_per_epoch, widgets=widgets)
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

Apparently, something was changed in the ProgressBar package recently. Quick look at the examples revealed that `maxval` arg should be used rather than `max_value`.
Original:
`pbar = ProgressBar(max_value = FLAGS.updates_per_epoch, widgets=widgets)`
Modified:
`pbar = ProgressBar(maxval = FLAGS.updates_per_epoch, widgets=widgets)
`
With this fix the package seems to work.

**Comment by tigerneil** [comment]
thanks @tsitsilin

**Comment by baniyan** [comment]
This helped me. @tsitsilin
